### ISSUE TITLE
replacing odrive with arduino

### ISSUE THREAD

**Issue by SithSyd** [maxipalay/minimec-ros2#1]
hi there, noticed that you are using odrive and leave a bit of space in the driver file for others to put their own driver to use on their robot. Can you walk me briefly on how to use arduino instead? Or is there a way to just use my own arduino control package with your package? Thank you

**Comment by maxipalay** [comment]
I'm just seeing this. You can basically scrap the driver node altogether and create your own. And what you need to provide/do on the one you create is:

- provide the necessary topics for the rest of the system to work (the main one being the joint states) 
- and subscribe to the topics you'd need to control your hardware (wheel commands)
 
Looking at the main ROS architecture diagram in this repo, you should also scrap the ODrive nodes and keep everything else. You shouldn't have any orphan arrows (pointing to nothing/having no source).
